name: talktive
description: "A simple anonymous group chat app"
publish_to: 'none'
version: 3.0.1+25

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  async: ^2.11.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  go_router: ^14.6.2
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  timeago: ^3.6.1
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  firebase_core_platform_interface: ^5.1.0
  firebase_auth_mocks: ^0.14.0
  fake_firebase_database:
    git: https://github.com/gnowoel/fake_firebase_database
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/icon-1024x1024-big.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground:  "assets/images/icon-1024x1024-small.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024-big.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
