name: talktive
description: "Talk without a trace."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  timeago: ^3.6.1
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core_platform_interface: ^5.1.0
  firebase_auth_mocks: ^0.14.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/icon-1024x1024-big.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground:  "assets/images/icon-1024x1024-small.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024-big.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
